/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../Layout/components/SettingModal/About.vue')['default']
    Account: typeof import('./../Layout/components/SettingModal/Account.vue')['default']
    Advanced: typeof import('./../Layout/components/SettingModal/Advanced.vue')['default']
    AdvancedSettings: typeof import('./../pages/SettingsPage/components/AdvancedSettings.vue')['default']
    ButtonGroup: typeof import('./../components/ButtonGroup.vue')['default']
    CategoriesDialog: typeof import('./../pages/RepoDetailPage/components/CategoriesDialog.vue')['default']
    Collapse: typeof import('./../components/Collapse/Collapse.vue')['default']
    CollapseItem: typeof import('./../components/Collapse/CollapseItem.vue')['default']
    CollectionCard: typeof import('./../pages/CollectionPage/components/CollectionCard.vue')['default']
    CollectionDeleteModal: typeof import('./../pages/CollectionPage/components/CollectionDeleteModal.vue')['default']
    CollectionDetailModal: typeof import('./../pages/CollectionPage/components/CollectionDetailModal.vue')['default']
    CollectionFormModal: typeof import('./../pages/CollectionPage/components/CollectionFormModal.vue')['default']
    CreateNoteModal: typeof import('./../components/CreateNoteModal.vue')['default']
    DeprecationWarning: typeof import('./../pages/DashboardPage/components/DeprecationWarning.vue')['default']
    HealthTab: typeof import('./../pages/RepoDetailPage/components/HealthTab.vue')['default']
    LoadingSpinner: typeof import('./../components/LoadingSpinner.vue')['default']
    MenuNav: typeof import('./../Layout/components/MenuNav.vue')['default']
    Message: typeof import('./../components/Message.vue')['default']
    Modal: typeof import('./../components/Modal.vue')['default']
    MyInput: typeof import('./../components/MyInput.vue')['default']
    MyInputNumber: typeof import('./../components/MyInputNumber.vue')['default']
    MySelect: typeof import('./../components/MySelect/index.vue')['default']
    MyTabPane: typeof import('./../components/MyTabs/MyTabPane.vue')['default']
    MyTabs: typeof import('./../components/MyTabs/MyTabs.vue')['default']
    Note: typeof import('./../Layout/components/SettingModal/Note.vue')['default']
    NoteEditor: typeof import('./../components/NoteEditor.vue')['default']
    NoteSettings: typeof import('./../pages/SettingsPage/components/NoteSettings.vue')['default']
    NoteTab: typeof import('./../pages/RepoDetailPage/components/NoteTab.vue')['default']
    Notification: typeof import('./../components/Notification.vue')['default']
    NotificationContainer: typeof import('./../components/NotificationContainer.vue')['default']
    Panel: typeof import('./../Layout/components/SettingModal/Panel.vue')['default']
    ProgressTab: typeof import('./../pages/RepoDetailPage/components/ProgressTab.vue')['default']
    ReadMeTab: typeof import('./../pages/RepoDetailPage/components/ReadMeTab.vue')['default']
    RecentlyActivity: typeof import('./../pages/DashboardPage/components/RecentlyActivity.vue')['default']
    RecentlyUpdate: typeof import('./../pages/DashboardPage/components/RecentlyUpdate.vue')['default']
    Repo: typeof import('./../Layout/components/SettingModal/Repo.vue')['default']
    RepoCard: typeof import('./../pages/ReposPage/components/RepoCard.vue')['default']
    RepoList: typeof import('./../pages/ReposPage/components/RepoList.vue')['default']
    RepoListModal: typeof import('./../pages/TagPage/components/RepoListModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./../components/SearchModal.vue')['default']
    SettingModal: typeof import('./../Layout/components/SettingModal/SettingModal.vue')['default']
    SettingsCard: typeof import('./../pages/SettingsPage/components/SettingsCard.vue')['default']
    Shortcut: typeof import('./../Layout/components/SettingModal/Shortcut.vue')['default']
    SideBar: typeof import('./../Layout/components/SideBar.vue')['default']
    StatusBar: typeof import('./../Layout/components/StatusBar.vue')['default']
    SwitchToggle: typeof import('./../components/SwitchToggle.vue')['default']
    TagDeleteModal: typeof import('./../pages/TagPage/components/TagDeleteModal.vue')['default']
    TagFormModal: typeof import('./../pages/TagPage/components/TagFormModal.vue')['default']
    Theme: typeof import('./../Layout/components/SettingModal/Theme.vue')['default']
    TiteBar: typeof import('./../Layout/components/TiteBar.vue')['default']
    VirtualScroll: typeof import('./../components/VirtualScroll.vue')['default']
  }
}
